AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  CodePipelineValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: validate.handler
      Runtime: nodejs10.x
      Policies:
       - CodePipelineLambdaExecutionPolicy: {}
  PipelineSlackAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: slackalert.lambda_handler
      Runtime: python2.7
      Environment:
        Variables:
          SLACK_CHANNEL: aws-alerts
          SLACK_USER: Pipelines
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/TimeResource/"
